CREATE TABLE IF NOT EXISTS "DP03Table" (
    year INTEGER,
    state VARCHAR(3),
    zipcode VARCHAR(5),
    total_population INTEGER,
    in_labor_force INTEGER,
    unemployment INTEGER,
    own_children6 INTEGER,
    own_children17 INTEGER,
    commute_car INTEGER,
    commute_time FLOAT,
    total_house INTEGER,
    inc_less_10k INTEGER,
    inc_10k_15k INTEGER,
    inc_15k_25k INTEGER,
    inc_25k_35k INTEGER,
    inc_35k_50k INTEGER,
    inc_50k_75k INTEGER,
    inc_75k_100k INTEGER,
    inc_100k_150k INTEGER,
    inc_150k_200k INTEGER,
    inc_more_200k INTEGER,
    with_social_security INTEGER,
    food_stamp INTEGER
);
